name: scroll_vanisher
description: Widget, that can make any widget hidable based on scroll direction.
version: 1.0.1
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
